# Generated by Django 5.1.4 on 2024-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('STUDIUM', 'Studium'), ('ARBEIT', 'Arbeit'), ('SPORT', 'Sport'), ('FAMILIE', 'Familie'), ('FREIZEIT', 'Freizeit')], max_length=100),
        ),
    ]
